apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: go-webclient
    context: go-webclient
    docker:
      dockerfile: Dockerfile
  - image: go-webserver
    context: go-webserver
    docker:
      dockerfile: Dockerfile
  - image: spring-webserver
    context: spring-webserver
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: go-webclient
      chartPath: go-webclient/charts
      artifactOverrides:
        image: go-webclient
      valuesFiles:
        - go-webclient/go-webclient-dev-values.yaml
    - name: go-webserver
      chartPath: go-webserver/charts
      artifactOverrides:
        image: go-webserver
      valuesFiles:
        - go-webserver/go-webserver-dev-values.yaml
    - name: spring-webserver
      chartPath: spring-webserver/charts
      artifactOverrides:
        image: spring-webserver
      valuesFiles:
        - spring-webserver/spring-webserver-dev-values.yaml
profiles:
- name: local-dev
  activation:
  - kubeContext: docker-desktop
- name: local-prod
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: go-webclient/go-webclient-prod-values.yaml
  - op: replace
    path: /deploy/helm/releases/1/valuesFiles/0
    value: go-webclient/go-webserver-prod-values.yaml
  - op: replace
    path: /deploy/helm/releases/2/valuesFiles/0
    value: spring-webserver/spring-webserver-prod-values.yaml
- name: cloud-dev
  build:
    artifacts:
    - image: docker.io/alitari/go-webclient
      context: go-webclient
      kaniko:
        noPush: false
        dockerfile: Dockerfile
        cache:
          repo: docker.io/alitari/go-webclient
    - image: docker.io/alitari/go-webserver
      context: go-webserver
      kaniko:
        noPush: false
        dockerfile: Dockerfile
        cache:
          repo: docker.io/alitari/go-webserver
    - image: docker.io/alitari/spring-webserver
      context: spring-webserver
      kaniko:
        noPush: false
        dockerfile: Dockerfile
        cache:
          repo: docker.io/alitari/spring-webserver
    cluster:
      pullSecretName: regcred
      namespace: default
      dockerConfig:
        secretName: kaniko-secret